apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverse-proxy
  name: reverse-proxy-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    service: reverse-proxy
