language: minimal

services:
  - docker

script:
  - docker --version
  - docker-compose -f docker/docker-compose-build.yml build

deploy:
  provider: script
  script: bash docker/docker_push.sh
  on:
    branch: master
